"""bind wechat

Revision ID: 1804876c9b60
Revises: 5242cbfe15aa
Create Date: 2018-08-29 12:03:40.569108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1804876c9b60'
down_revision = '5242cbfe15aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bo_users_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_bo_users_id'), 'users', ['bo_users_id'], unique=False)
    op.create_foreign_key(None, 'users', 'bo_users', ['bo_users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_bo_users_id'), table_name='users')
    op.drop_column('users', 'bo_users_id')
    # ### end Alembic commands ###
