"""disable role

Revision ID: 5242cbfe15aa
Revises: a468e4908c9a
Create Date: 2018-08-21 18:45:57.748453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5242cbfe15aa'
down_revision = 'a468e4908c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bo_roles', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bo_roles', 'disabled_at')
    # ### end Alembic commands ###
