"""role permissions

Revision ID: a468e4908c9a
Revises: 26b56fd7a0cd
Create Date: 2018-08-20 19:24:18.938636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a468e4908c9a'
down_revision = '26b56fd7a0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_role_x_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['bo_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bo_role_x_permissions_permission'), 'bo_role_x_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_bo_role_x_permissions_role_id'), 'bo_role_x_permissions', ['role_id'], unique=False)
    op.drop_table('bo_roles_permissions')
    op.drop_table('bo_permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_permissions',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('bo_permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bo_permissions_pkey'),
    sa.UniqueConstraint('name', name='bo_permissions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bo_roles_permissions',
    sa.Column('bo_permission_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bo_role_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bo_permission_id'], ['bo_permissions.id'], name='bo_roles_permissions_bo_permission_id_fkey'),
    sa.ForeignKeyConstraint(['bo_role_id'], ['bo_roles.id'], name='bo_roles_permissions_bo_role_id_fkey')
    )
    op.drop_index(op.f('ix_bo_role_x_permissions_role_id'), table_name='bo_role_x_permissions')
    op.drop_index(op.f('ix_bo_role_x_permissions_permission'), table_name='bo_role_x_permissions')
    op.drop_table('bo_role_x_permissions')
    # ### end Alembic commands ###
