"""initial db

Revision ID: a6a1a5eaf524
Revises: 
Create Date: 2018-08-16 12:34:44.836158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6a1a5eaf524'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bo_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task', sa.Unicode(), nullable=True),
    sa.Column('traceback', sa.Unicode(), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('openid', sa.Unicode(), nullable=True),
    sa.Column('mobile', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('bo_roles_permissions',
    sa.Column('bo_permission_id', sa.BigInteger(), nullable=True),
    sa.Column('bo_role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bo_permission_id'], ['bo_permissions.id'], ),
    sa.ForeignKeyConstraint(['bo_role_id'], ['bo_roles.id'], )
    )
    op.create_table('bo_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('nickname', sa.Unicode(), nullable=True),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.Column('mobile', sa.Unicode(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['bo_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bo_users')
    op.drop_table('bo_roles_permissions')
    op.drop_table('users')
    op.drop_table('task_errors')
    op.drop_table('bo_roles')
    op.drop_table('bo_permissions')
    # ### end Alembic commands ###
