"""alter user table

Revision ID: d1760f328ee3
Revises: 16e4955fffad
Create Date: 2025-03-14 15:22:47.122147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1760f328ee3'
down_revision = '16e4955fffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_errors')
    op.alter_column('bo_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bo_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bo_users', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('users', sa.Column('nickname', sa.Unicode(), nullable=True))
    op.add_column('users', sa.Column('avatar_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_bo_users_id', table_name='users')
    op.create_index(op.f('ix_users_avatar_id'), 'users', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_disabled_at'), 'users', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.drop_constraint('users_bo_users_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_avatar_id_fkey', 'users', 'media', ['avatar_id'], ['id'])
    op.drop_column('users', 'bo_users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bo_users_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('users_avatar_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key('users_bo_users_id_fkey', 'users', 'bo_users', ['bo_users_id'], ['id'])
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_disabled_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_avatar_id'), table_name='users')
    op.create_index('ix_users_bo_users_id', 'users', ['bo_users_id'], unique=False)
    op.drop_column('users', 'disabled_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'nickname')
    op.alter_column('bo_users', 'role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('bo_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bo_users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('task_errors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='task_errors_pkey')
    )
    # ### end Alembic commands ###
